blank_issues_enabled: false
contact_links:
  - name: Translation issues
    url: https://crowdin.com/project/tenno-companion
    about: For missing or incorrect translations, please use the Crowdin project.
