import { ChecklistTask } from './types'

export const DAILY_TASKS: ChecklistTask[] = [
  {
    id: 'daily-login-reward',
    title: 'checklist.daily.tasks.login',
  },
  {
    id: 'daily-forma',
    title: 'checklist.daily.tasks.craftForma',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.foundry',
  },
  {
    id: 'daily-other-foundry',
    title: 'checklist.daily.tasks.craftOther',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.foundry',
  },
  {
    id: 'daily-syndicate-standing',
    title: 'checklist.daily.tasks.factionSyndicates',
    info: 'checklist.daily.tasks.factionSyndicatesInfo',
  },
  {
    id: 'daily-arbitration',
    title: 'checklist.daily.tasks.arbitration',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.erisJunction',
  },
  {
    id: 'daily-nightwave',
    title: 'checklist.daily.tasks.nightwave',
    info: 'checklist.daily.tasks.nightwaveInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.nightwave',
  },
  {
    id: 'daily-world-syndicates',
    title: 'checklist.daily.tasks.worldSyndicates',
    checkable: false,
    subitems: [
      {
        id: 'daily-world-simaris',
        title: 'checklist.daily.tasks.cephalonSimaris',
        location: 'locations.anyRelay',
      },
      {
        id: 'daily-world-ostron',
        title: 'checklist.daily.tasks.ostron',
        location: 'locations.cetus',
        prerequisite: 'quests.sayasVigil',
      },
      {
        id: 'daily-world-quills',
        title: 'checklist.daily.tasks.theQuills',
        location: 'locations.cetus',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-solaris-united',
        title: 'checklist.daily.tasks.solarisUnited',
        location: 'locations.fortuna',
        prerequisite: 'quests.voxSolaris',
      },
      {
        id: 'daily-world-vox-solaris',
        title: 'checklist.daily.tasks.voxSolaris',
        location: 'locations.fortuna',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-ventkids',
        title: 'checklist.daily.tasks.ventkids',
        location: 'locations.fortuna',
        prerequisite: 'quests.voxSolaris',
      },
      {
        id: 'daily-world-entrati',
        title: 'checklist.daily.tasks.entrati',
        location: 'locations.necralisk',
        prerequisite: 'quests.heartOfDeimos',
      },
      {
        id: 'daily-world-necraloid',
        title: 'checklist.daily.tasks.necraloid',
        location: 'locations.necralisk',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-holdfasts',
        title: 'checklist.daily.tasks.theHoldfasts',
        location: 'locations.chrysalith',
        prerequisite: 'quests.angelsOfTheZariman',
      },
      {
        id: 'daily-world-cavia',
        title: 'checklist.daily.tasks.cavia',
        location: 'locations.sanctumAnatomica',
        prerequisite: 'quests.whispersInTheWalls',
      },
      {
        id: 'daily-world-hex',
        title: 'checklist.daily.tasks.theHex',
        location: 'locations.hollvaniaCentralMall',
        prerequisite: 'quests.theHex',
      },
    ],
  },
  {
    id: 'daily-sortie',
    title: 'checklist.daily.tasks.sortie',
    info: 'checklist.daily.tasks.sortieInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theWarWithin',
  },
  {
    id: 'daily-focus',
    title: 'checklist.daily.tasks.focus',
    info: 'checklist.daily.tasks.focusInfo',
    prerequisite: 'quests.theSecondDream',
  },
  {
    id: 'daily-vendors',
    title: 'checklist.daily.tasks.vendors',
    subitems: [
      {
        id: 'daily-vendor-acrithis',
        title: 'npcs.acrithis',
        info: 'checklist.daily.tasks.acrithisInfo',
        location: 'locations.dormizone',
        npc: 'npcs.acrithis',
      },
      {
        id: 'daily-vendor-ticker',
        title: 'npcs.ticker',
        info: 'checklist.daily.tasks.tickerInfo',
        location: 'locations.fortuna',
        npc: 'npcs.ticker',
        prerequisite: 'quests.risingTide',
      },
      {
        id: 'daily-vendor-marie',
        title: 'npcs.marie',
        info: 'checklist.daily.tasks.marieInfo',
        location: 'locations.laCathedrale',
        npc: 'npcs.marie',
        prerequisite: 'quests.theOldPeace',
      },
    ],
  },
]

export const WEEKLY_TASKS: ChecklistTask[] = [
  {
    id: 'weekly-nightwave',
    title: 'checklist.weekly.tasks.nightwave',
    info: 'checklist.weekly.tasks.nightwaveInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.nightwave',
  },
  {
    id: 'weekly-maroo',
    title: 'checklist.weekly.tasks.ayatanTreasureHunt',
    info: 'checklist.weekly.tasks.ayatanTreasureHuntInfo',
    location: 'locations.marooBazaar',
    npc: 'npcs.maroo',
  },
  {
    id: 'weekly-help-clem',
    title: 'checklist.weekly.tasks.helpClem',
    location: 'locations.anyRelay',
    npc: 'npcs.darvo',
    prerequisite: 'quests.aManOfFewWords',
  },
  {
    id: 'weekly-archon-hunt',
    title: 'checklist.weekly.tasks.archonHunt',
    info: 'checklist.weekly.tasks.archonHuntInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theNewWar',
  },
  {
    id: 'weekly-circuit-normal',
    title: 'checklist.weekly.tasks.circuit',
    info: 'checklist.weekly.tasks.circuitInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theDuviriParadox',
  },
  {
    id: 'weekly-circuit-sp',
    title: 'checklist.weekly.tasks.circuitSP',
    info: 'checklist.weekly.tasks.circuitSPInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theDuviriParadox',
  },
  // {
  //   id: 'weekly-netracells',
  //   title: 'Use weekly Netracell entries',
  //   location: 'Sanctum Anatomica, Deimos > Tagfer',
  //   terminal: 'Whispers in the Walls',
  // },
  // {
  //   id: 'weekly-eda',
  //   title: 'Attempt Elite Deep Archimedea',
  //   location: 'Sanctum Anatomica, Deimos > Necraloid',
  //   terminal: 'Rank 5 Cavia',
  // },
  // {
  //   id: 'weekly-helminth',
  //   title: 'Use Helminth invigorations',
  //   location: 'Orbiter > Helminth room',
  //   terminal: 'Helminth Segment and Rank 5 Entrati',
  // },
  // {
  //   id: 'weekly-vendors',
  //   title: 'Check weekly vendor rotations',
  //   location: 'Relays and open world hub vendors',
  //   terminal: 'Vendor-specific progression',
  // },
]

export const OTHER_TASKS: ChecklistTask[] = [
  {
    id: 'other-baro',
    title: "Baro Ki'Teer visit",
    location: 'Any active relay with Baro icon',
    terminal: 'Relay access and Ducats',
  },
  // {
  //   id: 'other-fissure-surge',
  //   title: 'Prime part stock refresh',
  //   location: 'Orbiter > Navigation > Void Fissures',
  //   terminal: 'Void Fissures unlocked',
  // },
  // {
  //   id: 'other-family-tokens',
  //   title: 'Mend the Family token purchases',
  //   location: 'Necralisk, Deimos > Grandmother',
  //   terminal: 'Heart of Deimos',
  // },
  // {
  //   id: 'other-zariman-turn-ins',
  //   title: 'Voidplume turn-ins and spending',
  //   location: 'Chrysalith, Zariman > Archimedean Yonta',
  //   terminal: 'Angels of the Zariman',
  // },
  // {
  //   id: 'other-sanctum-voca',
  //   title: 'Voca turn-ins and spending',
  //   location: 'Sanctum Anatomica, Deimos > Loid',
  //   terminal: 'Whispers in the Walls',
  // },
  // {
  //   id: 'other-goal-cleanup',
  //   title: 'Goal-based cleanup',
  //   location: 'Varies by event or farm route',
  //   terminal: 'Varies by objective',
  // },
]
