import { ChecklistTask } from './types'

export const DAILY_TASKS: ChecklistTask[] = [
  {
    id: 'daily-login-reward',
    title: 'checklist.daily.tasks.login',
  },
  {
    id: 'daily-forma',
    title: 'checklist.daily.tasks.craftForma',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.foundry',
  },
  {
    id: 'daily-other-foundry',
    title: 'checklist.daily.tasks.craftOther',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.foundry',
  },
  {
    id: 'daily-syndicate-standing',
    title: 'checklist.daily.tasks.factionSyndicates',
    info: 'checklist.daily.tasks.factionSyndicatesInfo',
  },
  {
    id: 'daily-arbitration',
    title: 'checklist.daily.tasks.arbitration',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'prerequisites.erisJunction',
  },
  {
    id: 'daily-nightwave',
    title: 'checklist.daily.tasks.nightwave',
    info: 'checklist.daily.tasks.nightwaveInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.nightwave',
  },
  {
    id: 'daily-world-syndicates',
    title: 'checklist.daily.tasks.worldSyndicates',
    checkable: false,
    subitems: [
      {
        id: 'daily-world-simaris',
        title: 'checklist.daily.tasks.cephalonSimaris',
        location: 'locations.anyRelay',
      },
      {
        id: 'daily-world-ostron',
        title: 'checklist.daily.tasks.ostron',
        location: 'locations.cetus',
        prerequisite: 'quests.sayasVigil',
      },
      {
        id: 'daily-world-quills',
        title: 'checklist.daily.tasks.theQuills',
        location: 'locations.cetus',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-solaris-united',
        title: 'checklist.daily.tasks.solarisUnited',
        location: 'locations.fortuna',
        prerequisite: 'quests.voxSolaris',
      },
      {
        id: 'daily-world-vox-solaris',
        title: 'checklist.daily.tasks.voxSolaris',
        location: 'locations.fortuna',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-ventkids',
        title: 'checklist.daily.tasks.ventkids',
        location: 'locations.fortuna',
        prerequisite: 'quests.voxSolaris',
      },
      {
        id: 'daily-world-entrati',
        title: 'checklist.daily.tasks.entrati',
        location: 'locations.necralisk',
        prerequisite: 'quests.heartOfDeimos',
      },
      {
        id: 'daily-world-necraloid',
        title: 'checklist.daily.tasks.necraloid',
        location: 'locations.necralisk',
        prerequisite: 'quests.theWarWithin',
      },
      {
        id: 'daily-world-holdfasts',
        title: 'checklist.daily.tasks.theHoldfasts',
        location: 'locations.chrysalith',
        prerequisite: 'quests.angelsOfTheZariman',
      },
      {
        id: 'daily-world-cavia',
        title: 'checklist.daily.tasks.cavia',
        location: 'locations.sanctumAnatomica',
        prerequisite: 'quests.whispersInTheWalls',
      },
      {
        id: 'daily-world-hex',
        title: 'checklist.daily.tasks.theHex',
        location: 'locations.hollvaniaCentralMall',
        prerequisite: 'quests.theHex',
      },
    ],
  },
  {
    id: 'daily-sortie',
    title: 'checklist.daily.tasks.sortie',
    info: 'checklist.daily.tasks.sortieInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theWarWithin',
  },
  {
    id: 'daily-focus',
    title: 'checklist.daily.tasks.focus',
    info: 'checklist.daily.tasks.focusInfo',
    prerequisite: 'quests.theSecondDream',
  },
  {
    id: 'daily-vendors',
    title: 'checklist.daily.tasks.vendors',
    subitems: [
      {
        id: 'daily-vendor-acrithis',
        title: 'npcs.acrithis',
        info: 'checklist.daily.tasks.acrithisInfo',
        location: 'locations.dormizone',
        npc: 'npcs.acrithis',
      },
      {
        id: 'daily-vendor-ticker',
        title: 'npcs.ticker',
        info: 'checklist.daily.tasks.tickerInfo',
        location: 'locations.fortuna',
        npc: 'npcs.ticker',
        prerequisite: 'quests.risingTide',
      },
      {
        id: 'daily-vendor-marie',
        title: 'npcs.marie',
        info: 'checklist.daily.tasks.marieInfo',
        location: 'locations.laCathedrale',
        npc: 'npcs.marie',
        prerequisite: 'quests.theOldPeace',
      },
    ],
  },
]

export const WEEKLY_TASKS: ChecklistTask[] = [
  {
    id: 'weekly-nightwave',
    title: 'checklist.weekly.tasks.nightwave',
    info: 'checklist.weekly.tasks.nightwaveInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.nightwave',
  },
  {
    id: 'weekly-maroo',
    title: 'checklist.weekly.tasks.ayatanTreasureHunt',
    info: 'checklist.weekly.tasks.ayatanTreasureHuntInfo',
    location: 'locations.marooBazaar',
    npc: 'npcs.maroo',
  },
  {
    id: 'weekly-help-clem',
    title: 'checklist.weekly.tasks.helpClem',
    location: 'locations.anyRelay',
    npc: 'npcs.darvo',
    prerequisite: 'quests.aManOfFewWords',
  },
  {
    id: 'weekly-archon-hunt',
    title: 'checklist.weekly.tasks.archonHunt',
    info: 'checklist.weekly.tasks.archonHuntInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theNewWar',
  },
  {
    id: 'weekly-circuit-normal',
    title: 'checklist.weekly.tasks.circuit',
    info: 'checklist.weekly.tasks.circuitInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theDuviriParadox',
  },
  {
    id: 'weekly-circuit-sp',
    title: 'checklist.weekly.tasks.circuitSP',
    info: 'checklist.weekly.tasks.circuitSPInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theDuviriParadox',
  },
  {
    id: 'weekly-search-pulses',
    title: 'checklist.weekly.tasks.searchPulses',
    info: 'checklist.weekly.tasks.searchPulsesInfo',
    subitems: [
      {
        id: 'weekly-search-pulses-netracells',
        title: 'checklist.weekly.tasks.netracells',
        info: 'checklist.weekly.tasks.netracellsInfo',
        location: 'locations.sanctumAnatomica',
        npc: 'npcs.tagfer',
        prerequisite: 'quests.whispersInTheWalls',
      },
      {
        id: 'weekly-search-pulses-deep-archimedea',
        title: 'checklist.weekly.tasks.eliteDeepArchimedea',
        info: 'checklist.weekly.tasks.eliteDeepArchimedeaInfo',
        location: 'locations.sanctumAnatomica',
        npc: 'npcs.necraloid',
        prerequisite: 'prerequisites.rank5Cavia',
      },
      {
        id: 'weekly-search-pulses-temporal-archimedea',
        title: 'checklist.weekly.tasks.eliteTemporalArchimedea',
        info: 'checklist.weekly.tasks.eliteTemporalArchimedeaInfo',
        location: 'locations.hollvaniaCentralMall',
        npc: 'npcs.kaya',
        prerequisite: 'prerequisites.rank5Hex',
      },
    ],
  },
  {
    id: 'weekly-1999-calendar',
    title: 'checklist.weekly.tasks.the1999Calendar',
    info: 'checklist.weekly.tasks.the1999CalendarInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.pom2pc',
    prerequisite: 'quests.theHex',
  },
  {
    id: 'weekly-helminth',
    title: 'checklist.weekly.tasks.helminth',
    info: 'checklist.weekly.tasks.helminthInfo',
    location: 'locations.baseOfOperations',
    terminal: 'terminal.helminth',
    prerequisite: 'prerequisites.rank5Entrati',
  },
  {
    id: 'weekly-descendia',
    title: 'checklist.weekly.tasks.descendia',
    info: 'checklist.weekly.tasks.descendiaInfo',
    location: 'locations.darkRefactory',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theOldPeace',
  },
  {
    id: 'weekly-descendia-steel-path',
    title: 'checklist.weekly.tasks.descendiaSteelPath',
    info: 'checklist.weekly.tasks.descendiaInfo',
    location: 'locations.darkRefactory',
    terminal: 'terminal.navigation',
    prerequisite: 'quests.theOldPeace',
  },
  {
    id: 'weekly-vendors',
    title: 'checklist.weekly.tasks.vendors',
    subitems: [
      {
        id: 'weekly-vendor-paladino',
        title: 'npcs.paladino',
        info: 'checklist.weekly.tasks.paladinoInfo',
        location: 'locations.ironWake',
        npc: 'npcs.paladino',
        prerequisite: 'quests.theChainsOfHarrow',
      },
      {
        id: 'weekly-vendor-yonta',
        title: 'npcs.yonta',
        info: 'checklist.weekly.tasks.yontaInfo',
        location: 'locations.chrysalith',
        npc: 'npcs.yonta',
        prerequisite: 'quests.angelsOfTheZariman',
      },
      {
        id: 'weekly-vendor-acrithis',
        title: 'npcs.acrithis',
        info: 'checklist.weekly.tasks.acrithisInfo',
        location: 'locations.dormizone',
        npc: 'npcs.acrithis',
        prerequisite: 'quests.theDuviriParadox',
      },
      {
        id: 'weekly-vendor-teshin',
        title: 'npcs.teshin',
        info: 'checklist.weekly.tasks.teshinInfo',
        location: 'locations.anyRelay',
        npc: 'npcs.teshin',
        prerequisite: 'prerequisites.steelPath',
      },
      {
        id: 'weekly-vendor-bird3',
        title: 'npcs.bird3',
        info: 'checklist.weekly.tasks.bird3Info',
        location: 'locations.sanctumAnatomica',
        npc: 'npcs.bird3',
        prerequisite: 'prerequisites.rank5Cavia',
      },
      {
        id: 'weekly-vendor-nightcap',
        title: 'npcs.nightcap',
        info: 'checklist.weekly.tasks.nightcapInfo',
        location: 'locations.fortuna',
        npc: 'npcs.nightcap',
        prerequisite: 'quests.theNewWar',
      },
    ],
  },
]

export const OTHER_TASKS: ChecklistTask[] = [
  {
    id: 'other-baro',
    title: 'npcs.baro',
    info: 'checklist.other.tasks.baroInfo',
    npc: 'npcs.baro',
    resets: 'baro',
  },
  {
    id: 'other-entrati-tokens',
    title: 'checklist.other.tasks.entratiTokens',
    info: 'checklist.other.tasks.entratiTokensInfo',
    location: 'locations.necralisk',
    npc: 'npcs.grandmother',
    prerequisite: 'quests.heartOfDeimos',
    resets: 'daily',
  },
  {
    id: 'other-voidplume-trade',
    title: 'checklist.other.tasks.voidplumeTrade',
    location: 'locations.chrysalith',
    npc: 'npcs.yonta',
    prerequisite: 'quests.angelsOfTheZariman',
    resets: 'daily',
  },
  {
    id: 'other-voca-trade',
    title: 'checklist.other.tasks.vocaTrade',
    location: 'locations.sanctumAnatomica',
    npc: 'npcs.loid',
    prerequisite: 'quests.whispersInTheWalls',
    resets: 'daily',
  },
]
