name: Automated Data Sync

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Update Check
        id: update
        continue-on-error: true
        run: pnpm --filter @tenno-companion/core run check-updates

      - name: Commit and Push to Main
        if: steps.update.outcome == 'failure' # Exit 1 from script
        run: |
          git config --global user.name "tennocompanion-bot"
          git config --global user.email "bot@tennocompanion.com"
          git add apps/* packages/*
          git commit -m "chore: sync warframe data [skip ci]"
          git push origin main

      - name: Build and Publish
        if: steps.update.outcome == 'failure'
        run: pnpm --filter @tenno-companion/core publish --access public --no-git-checks --provenance
